#ifndef VRINPUT_H_
#define VRINPUT_H_

#include <irrlicht.h>
using namespace irr;

enum shifts {
	KB_SHIFT_FLAG=1
};
enum keys {
	VR_KEY_X, VR_KEY_Z, VR_KEY_C, VR_KEY_V, VR_KEY_UP, VR_KEY_DOWN, VR_KEY_LEFT, VR_KEY_RIGHT, VR_KEY_ESC,
	VR_KEY_CREDIT, VR_KEY_START
};
enum player1_keys {
	VR_P1_KEY_X = KEY_KEY_X, VR_P1_KEY_Z = KEY_KEY_Z, 
	VR_P1_KEY_C = KEY_KEY_C, VR_P1_KEY_V = KEY_KEY_V,
	VR_P1_KEY_UP = KEY_UP, VR_P1_KEY_DOWN = KEY_DOWN,
	VR_P1_KEY_LEFT = KEY_LEFT, VR_P1_KEY_RIGHT = KEY_RIGHT, VR_P1_KEY_ESC = KEY_ESCAPE,

	VR_P1_KEY_CREDIT = KEY_KEY_1, VR_P1_KEY_START = KEY_KEY_2
};
enum player2_keys {
	VR_P2_KEY_X = KEY_KEY_R, VR_P2_KEY_Z = KEY_KEY_T,
	VR_P2_KEY_C = KEY_KEY_Y, VR_P2_KEY_V = KEY_KEY_U,
	VR_P2_KEY_UP = KEY_KEY_O, VR_P2_KEY_DOWN = KEY_KEY_L,
	VR_P2_KEY_LEFT = KEY_KEY_I, VR_P2_KEY_RIGHT = KEY_KEY_P, VR_P2_KEY_ESC = KEY_KEY_K,

	VR_P2_KEY_CREDIT = KEY_KEY_5, VR_P2_KEY_START = KEY_KEY_6
};
enum player3_keys {
	VR_P3_KEY_X = KEY_KEY_A, VR_P3_KEY_Z = KEY_KEY_S,
	VR_P3_KEY_C = KEY_KEY_D, VR_P3_KEY_V = KEY_KEY_F,
	VR_P3_KEY_UP = KEY_KEY_H, VR_P3_KEY_DOWN = KEY_KEY_N,
	VR_P3_KEY_LEFT = KEY_KEY_G, VR_P3_KEY_RIGHT = KEY_KEY_J, VR_P3_KEY_ESC = KEY_KEY_B,

	VR_P3_KEY_CREDIT = KEY_KEY_8, VR_P3_KEY_START = KEY_KEY_9
};

#endif /*VRINPUT_H_*/
